services:
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  test_script:
    build: .
    environment:
      - NODE_ENV=production
      - DOCKER=true
    depends_on:
      - redis
  # postgres:
  #   image: postgres
  #   container_name: postgres
  #   environment:
  #     POSTGRES_DB: cities
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: mypassword
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - ./psql-cities-data/world.sql:/docker-entrypoint-initdb.d/world.sql
