services:
  redis:
    image: redis:alpine
    container_name: redis-alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:alpine
    container_name: postgres-alpine
    environment:
      POSTGRES_DB: cities
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
        - "5432:5432"
    volumes:
      - ./psql-cities-data/world.sql:/docker-entrypoint-initdb.d/world.sql
